### ISSUE TITLE
Store Run Info and Summary Data On Model Components

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#58]
This builds on the previous  data model:
- Create a property to hold run on the model element (riversegment) named with the scenario name, varkey = "om_scenario", for CBP models that is easy, and for vahydro use the convention "runid_" + the runid (i.e. 120, 121,...)
- Attach any run summary data, such as flow metrics to this scenario info property (i.e. "runid_121") as sub-properties
- If we do a gage weighted analysis, that is a sub-property of the scenario property

See slide below:
![image](https://user-images.githubusercontent.com/4571170/69191006-961a7800-0aef-11ea-8057-d8a2868b3c0c.png)

**Comment by hdaniel7** [comment]
I've been working on getting (and posting, if they do not yet exist) these properties -- [here's an R script](https://github.com/HARPgroup/cbp6/blob/master/R/get.scen.prop.R) of what I've got so far, and an example of the property it creates is contained within [this property](http://deq2.bse.vt.edu/d.dh/admin/content/dh_properties/manage/4733130/dh_properties).   That said, I've run into a few issues --

- From what I can tell, the propcode has to be numeric.  When I try to update the propvalue to a string such as "finished", it returns [Error 406](https://airbrake.io/blog/http-errors/406-not-acceptable), seemingly relating to passing data in a form that the server refuses to accept.
- I also can't determine what format is acceptable to pass startdate or enddate information -- I've tried the classic "yyyy-mm-dd" as well as as.Date("yyyy-mm-dd"), as well as a few other common date formats, but I haven't found anything that doesn't also return an Error 406. 

To check that I'm posting these properties in the right location, here's a quick overview:

- [http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/67902](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/67902) is the overall river segment watershed page for river segment JU3_7400_7510

- [Attached to this property](http://deq2.bse.vt.edu/d.dh/admin/content/dh_features/manage/67902/dh_properties) are two (old) properties for the two model scenarios we have as of yet 
![ex1](https://user-images.githubusercontent.com/36606075/69925596-0aa1cf00-147f-11ea-828d-25ea49d44d96.PNG)

- [Within the base scenario property](http://deq2.bse.vt.edu/d.dh/admin/content/dh_properties/manage/4733130/dh_properties) are the properties described in this issue -- currently, with incorrect propvalue and no startdate/enddate
![ex2](https://user-images.githubusercontent.com/36606075/69925599-1392a080-147f-11ea-8cc2-67c4fb86b61d.PNG)

**Comment by rburghol** [comment]
Daniel - thanks.  Two things:
- Numeric data should be in propvalue -- I didn't flesh out this clearly in the original data model above.  Those codes, init, running, finished, each correspond to a different integer value as follows:
  - 0 - finished, 1 - running, 2 - editing, 3 - initializing
  - You will only be using code 0 at this time
- The starttime and endtime need to be submitted as a Unix timestamp, which is actually an integer value.Example below:
```
sceninfo$startdate <- as.numeric(as.POSIXct(start.date,origin = "1970-01-01", tz = "GMT"))
sceninfo$enddate <- as.numeric(as.POSIXct(end.date,origin = "1970-01-01", tz = "GMT"))
```

**Comment by rburghol** [comment]
Daniel - I just updated the code on the deq2 server to handle the startdate and enddate parameters properly (*I think*) - can you test it out and let me know?

**Comment by hdaniel7** [comment]
I've tried running the "as.numeric(as.POSIXct(start.date,origin = "1970-01-01", tz = "GMT"))" line, as well as changing as.numeric() to as.integer() and as.character() -- none of these are working for me (still getting the Error 406).

Since the code you updated was on the deq2 server, there was nothing I had to update to test these startdate and enddate parameters, correct?

**Comment by hdaniel7** [comment]
[get.scen.prop.R](https://github.com/HARPgroup/cbp6/blob/master/R/get.scen.prop.R) gets (or posts, if the property does not exist) the scenario property described in this issue.  At the moment, it still does not support startdate or enddate parameters.

[vahydro.post.metric.to.scenprop](https://github.com/HARPgroup/cbp6/blob/master/R/vahydro_post_metric_to_scenprop.R) posts a single metric to the created scenario property

[vahydro_post_all_metrics_to_scenprop.R](https://github.com/HARPgroup/cbp6/blob/master/R/vahydro_post_all_metrics_to_scenprop.R) posts all of the metrics in our "original six" tables to the scenario property

We can also talk about whether we want to store our calculated land-river segment metrics on the associated land-river segments -- these include local runoff inflow metrics, flow metrics by type (suro, ifwo, agwo) and annual flow metrics.

I'm working on incorporating these functions into the modularized dashboard -- I'll post again about any developments in this

**Comment by rburghol** [comment]
Daniel - this is good stuff.  When you get a chance, if you could post your test script up in the R/examples folder of this repo, that would be cool.  It would insure that we are testing on the same case, and save me or Joey about 15 minutes trying to replicate the use case.  

I like the way you split the function up into a single metric posting widget, then a batch that calls it for all of our "original six".

**Comment by hdaniel7** [comment]
Yup -- this is the test script I used to generate the dashboard up on http://deq2.bse.vt.edu/p6/p6_gb604/out/dashboards/run_120_vs_run_121/ :

Rscript -e "rmarkdown::render('~/cbp6/code/Modularized_Dashboard.Rmd', output_dir = '/opt/model/p6/p6_gb604/out/dashboards/run_120_vs_run_121', output_file = 'JU1_7690_7490.pdf', params = list(riv.seg = 'JU1_7690_7490', dat.source1 = 'vahydro', dat.source2 = 'vahydro', start.date = '1984-01-01', end.date = '2000-12-31', github_link = '~', site = 'http://deq2.bse.vt.edu/d.dh', site.or.server = 'server', run.id1 = '120', run.id2 = '121', gage_number = FALSE, mod.phase1 = 'p6/p6_gb604', mod.scenario1 = 'CFBASE30Y20180615', mod.phase2 = 'p6/p6_gb604', mod.scenario2 = 'CBASE1808L55CY55R45P50R45P50Y'))"

Emma noticed that the map is wrong and doesn't update between dashboard runs -- it turns out I never implemented the function which generates the figure into the script, just the one that calls it.  I'm running into some issues with the scalebar() and north() functions in the ggsn package when running it on the server, but I'll keep you updated when that aspect is functional

**Comment by hdaniel7** [comment]
The GIS figure is now working as well -- it turns out that passing gage_number = FALSE is what broke the script -- instead passing gage_number = '00000000' allows everything to run properly when there is no associated gage. I'll make some further changes in the script to make this a bit more intuitive soon. For now, the command 

```Rscript -e "rmarkdown::render('~/cbp6/code/Modularized_Dashboard.Rmd', output_dir = '/opt/model/p6/p6_gb604/out/dashboards/run_120_vs_run_121', output_file = 'JU1_7690_7490.pdf', params = list(riv.seg = 'JU1_7690_7490', dat.source1 = 'vahydro', dat.source2 = 'vahydro', start.date = '1984-01-01', end.date = '2000-12-31', github_link = '~', site = 'http://deq2.bse.vt.edu/d.dh', site.or.server = 'server', run.id1 = '120', run.id2 = '121', gage_number = '00000000', mod.phase1 = 'p6/p6_gb604', mod.scenario1 = 'CFBASE30Y20180615', mod.phase2 = 'p6/p6_gb604', mod.scenario2 = 'CBASE1808L55CY55R45P50R45P50Y'))"```

should work to generate a dashboard with the proper GIS map.  I'll clean up the dashboards and remove some of the unnecessary printed results in a few hours.

**Comment by hdaniel7** [comment]
Dashboards are fixed, up, and running -- here's a comment with further information:

https://github.com/HARPgroup/cbp6/issues/145#issuecomment-561832245

**Comment by rburghol** [comment]
Daniel -- just reviewing this: so far this looks like it is functioning great.  There are 2 tweaks we need:
1. The naming convention of the scenario property doesn't match the above.  The dashboards scripts are saving as "run_11" rather than "runid_11".  I have used VBO to rename all the existing run summaries, so no re-runs will be needed at this time, but future runs should follow the convention.
2. Add a file with propname 'dashboard_file', which contains the URL to the pdf.  We will later generate image files for some of the key visualizations (like fig1.hydrograph, and fig2.zoomed.hydrograph) and store their paths likewise, so this will be a good start.

Thanks!
/r/b

**Comment by hdaniel7** [comment]
I've made the tweaks -- here's a link to the river segment I was testing the updated dashboard creator on: http://deq2.bse.vt.edu/d.dh/admin/content/dh_properties/manage/4713788/dh_properties.

I'm not a huge fan of how using a URL in the propcode of the "dashboard_file" property stretches the propcode column so severely -- do you have any ideas of alternative ways of linking this property which might work better? Or, do you think this URL should be stored instead within every scenario property it involves (i.e., this "dashboard_file" property instead stored both inside the "runid_11" and "runid_14" scenario properties)?

**Comment by rburghol** [comment]
Daniel -- per our conversation, I had a notion about why the model run results properties might being overwritten by our respective scripts.  I have been using "vahydro-1.0" as the propcode, based largely on the fact that in my automated post-process routine I don't have a way to determine the flow scenario code like you do (is.e. cfbase...).  That *might* be why my summaries are replacing yours, and if that's happening, when you re-do your summaries they will replace mine.  I *think* that if we either:
1) Use the same propcode, "vahydro-1.0", then set another property on the scenario "flow_mode", with a propcode of "CFBASE...", or 
2) Only give the propname when we retrieve the scenario, then write whatever we want in the propcode (i.e. CFBASE...).

I like the detail that your propcode allows, but don't see a way to get it in mine via an automated method, which is a HUGE benefit to our workflow.

**Comment by hdaniel7** [comment]
Rob, I like the first idea (using the 'vahydro-1.0' propcode and creating "flow_mode" properties within that property with propcodes of the corresponding scenario names) -- it seems like this will leave your workflow automated while also allowing ours to remain automated and piggyback off of yours.   I'll try to implement this into the dashboard script early next week (for right now, my top priorities are to finish generating precip/temp metric maps, begin creating lrseg Runit metric and lat/long maps, and start the overleaf write-up prior to the meeting early next week).

**Comment by rburghol** [comment]
Hey all - I have tweaked and tested the data retrieval to pass all the data for a given runid for a single riverseg.  Seems to be working quite nicely.  Here is an example set of paramters for use with the view we shared yesterday (will put it in an email and on Overleaf).  

Retrieve Clink River params for runid_13:
entity-model-prop-level/67752/dh_feature/watershed/vahydro/vahydro-1.0/runid_13/all
 @emmaa4 @jdkleiner @kevindandrea @hdaniel7 @laljeet
